13 00 00 00 #                  ADDI    x0, x0, 0          # 0      # ----- Small Positive Numbers -----                                                                                                                                                                                                    
93 00 60 00 #                  ADDI    x1, x0, 6          # 4      # x1 = 6                                                                                                                                                
13 01 30 00 #                  ADDI    x2, x0, 3          # 8      # x2 = 3                                                                                                                                                
B3 81 20 02 #                  MUL     x3, x1, x2         # 12     # x3 = 6 * 3 = 18                                                                                                                                               
33 C2 20 02 #                  DIV     x4, x1, x2         # 16     # x4 = 6 / 3 = 2                                                                                                                                                
B3 E2 20 02 #                  REM     x5, x1, x2         # 20     # x5 = 6 % 3 = 0                                                                                                                                                
13 01 50 00 #                  ADDI    x2, x0, 5          # 24     # x2 = 5                                                                                                                                                
B3 E2 20 02 #                  REM     x5, x1, x2         # 28     # x5 = 6 % 5 = 1                                                                                                                                                
13 00 00 00 #                  ADDI    x0,  x0, 0         # 32     # ----- Small Negative and Positive -----                                                                                                                                               
13 03 70 FF #                  ADDI    x6,  x0, -9        # 36     # x6 = -9                                                                                                                                               
93 03 40 00 #                  ADDI    x7,  x0, 4         # 40     # x7 = 4                                                                                                                                                
33 04 73 02 #                  MUL     x8,  x6, x7        # 44     # x8 = -9 * 4 = -36                                                                                                                                             
B3 44 73 02 #                  DIV     x9,  x6, x7        # 48     # x9 = -9 / 4 = -2                                                                                                                                              
33 65 73 02 #                  REM     x10, x6, x7        # 52     # x10 = -9 % 4 = -1                                                                                                                                             
13 00 00 00 #                  ADDI    x0,  x0,  0        # 56     # ----- Both Negative -----                                                                                                                                             
93 05 40 FF #                  ADDI    x11, x0, -12       # 60     # x11 = -12                                                                                                                                             
13 06 B0 FF #                  ADDI    x12, x0, -5        # 64     # x12 = -5                                                                                                                                              
B3 86 C5 02 #                  MUL     x13, x11, x12      # 68     # x13 = -12 * -5 = 60                                                                                                                                               
33 C7 C5 02 #                  DIV     x14, x11, x12      # 72     # x14 = -12 / -5 = 2                                                                                                                                                
B3 E7 C5 02 #                  REM     x15, x11, x12      # 76     # x15 = -12 % -5 = -2                                                                                                                                               
13 00 00 00 #                  ADDI    x0,  x0, 0         # 80     # ----- Larger Positive Operands -----                                                                                                                                              
37 38 12 00 #                  LUI     x16, 0x00123       # 84     # x16 = 0x00123000 = 1191936                                                                                                                                                      
13 08 68 45 #                  ADDI    x16, x16, 0x456    # 88     # x16 = 0x00123456 = 1193046                                                                                                                                                
B7 98 08 00 #                  LUI     x17, 0x00089       # 92     # x17 = 0x00089000 = 561152                                                                                                                                                   
93 88 18 32 #                  ADDI    x17, x17, 0x321    # 96     # x17 = 0x00089321 = 561057                                                                                                                                             
33 09 18 03 #                  MUL     x18, x16, x17      # 100    # x18 = 1193046 * 561057 (low 32 bits) = 0x9C_1916_2116 = 420880662                                                                                                                                             
B3 19 18 03 #                  MULH    x19, x16, x17      # 104    # x19 = high 32 bits of signed product = 0x9C = 156                                                                                                                                              
13 00 00 00 #                  ADDI    x0,  x0,  0        # 108    # ----- Large Positive × Negative -----                                                                                                                                             
13 0A F0 FE #                  ADDI    x20, x0, -17       # 112    # x20 = -17                                                                                                                                             
B3 0A 48 03 #                  MUL     x21, x16, x20      # 116    # x21 = 1193046 * -17 = -20281782                                                                                                                                               
33 1B 48 03 #                  MULH    x22, x16, x20      # 120    # x22 = upper 32 bits of signed result = 0xFFFF_FFFF = -1                                                                                                                                              
13 00 00 00 #                  ADDI    x0,  x0,  0        # 124    # ----- Unsigned Multiplication Tests -----                                                                                                                                             
93 0B F0 FF #                  ADDI    x23, x0,  -1       # 128    # x23 = 0xFFFFFFFF = -1                                                                                                                                              
13 0C 00 01 #                  ADDI    x24, x0,  0x10     # 132    # x24 = 16                                                                                                                                              
B3 BC 8B 03 #                  MULHU   x25, x23, x24      # 136    # x25 = high 32 bits of 0xFFFFFFFF * 0x10 = 0x0000_000F_(_FFFF_FFF0) = 15                                                                                                                                              
33 AD 8B 03 #                  MULHSU  x26, x23, x24      # 140    # x26 = signed x23 * unsigned x24 = 0xFFFF_FFFF_(_FFFF_FFF0) = -1                                                                                                                                     
13 00 00 00 #                  ADDI    x0,  x0,  0        # 144    # -----  Unsigned Division -----                                                                                                                                                
93 0D F0 FF #                  ADDI    x27, x0,  -1       # 148    # x27 = 0xFFFFFFFF (unsigned = 4294967295) = -1                                                                                                                                             
13 0E 20 00 #                  ADDI    x28, x0,  2        # 152    # x28 = 2                                                                                                                                               
B3 DE CD 03 #                  DIVU    x29, x27, x28      # 156    # x29 = 0xFFFFFFFF / 2 = 2147483647                                                                                                                                             
33 FF CD 03 #                  REMU    x30, x27, x28      # 160    # x30 = 0xFFFFFFFF % 2 = 1                                                                                                                                              
13 00 00 00 #                  ADDI    x0,  x0,  0        # 164    # ----- Unsigned division of small values -----                                                                                                                                             
93 0F 40 06 #                  ADDI    x31, x0,  100      # 168    # x31 = 100                                                                                                                                             
93 02 70 00 #                  ADDI    x5,  x0,  7        # 172    # x5  = 7                                                                                                                                               
33 D3 5F 02 #                  DIVU    x6,  x31, x5       # 176    # x6 = 100 / 7 = 14                                                                                                                                             
B3 F3 5F 02 #                  REMU    x7,  x31, x5       # 180    # x7 = 100 % 7 = 2                                                                                                                                              
13 00 00 00 #                  ADDI    x0,  x0, 0         # 184    # ----- Divide by zero (should return 0 for Quotient and Remainder) -----                                                                                                                                               
13 04 B0 07 #                  ADDI    x8,  x0, 123       # 188    # x8 = 123                                                                                                                                              
93 04 00 00 #                  ADDI    x9,  x0, 0         # 192    # x9 = 0                                                                                                                                                
33 45 94 02 #                  DIV     x10, x8, x9        # 196    # x10 = 123 / 0 = undefined (return 0)                                                                                                                                              
B3 65 94 02 #                  REM     x11, x8, x9        # 200    # x11 = 123 % 0 = undefined (return 0)                                                                                                                                              
33 56 94 02 #                  DIVU    x12, x8, x9        # 204    # x12 = same, unsigned (return 0)                                                                                                                                               
B3 76 94 02 #                  REMU    x13, x8, x9        # 208    # x13 = same, (return 0)  

B7 00 AD DE #                  LUI     x1,  0xDEAD0       # 212                                                                                                                                            
37 01 AD DE #                  LUI     x2,  0xDEAD0       # 216    # 0xDEAD_0000 = -559087616                                                                                                                                         
B7 01 AD DE #                  LUI     x3,  0xDEAD0       # 220                                                                                                                                            
37 02 AD DE #                  LUI     x4,  0xDEAD0       # 224                                                                                                                                            
B7 02 AD DE #                  LUI     x5,  0xDEAD0       # 228                                                                                                                                            
37 03 AD DE #                  LUI     x6,  0xDEAD0       # 232                                                                                                                                            
B7 03 AD DE #                  LUI     x7,  0xDEAD0       # 236                                                                                                                                            
37 04 AD DE #                  LUI     x8,  0xDEAD0       # 240                                                                                                                                            
B7 04 AD DE #                  LUI     x9,  0xDEAD0       # 244                                                                                                                                            
37 05 AD DE #                  LUI     x10, 0xDEAD0       # 248                                                                                                                                            
B7 05 AD DE #                  LUI     x11, 0xDEAD0       # 252                                                                                                                                            
37 06 AD DE #                  LUI     x12, 0xDEAD0       # 256                                                                                                                                            
B7 06 AD DE #                  LUI     x13, 0xDEAD0       # 260                                                                                                                                            
37 07 AD DE #                  LUI     x14, 0xDEAD0       # 264                                                                                                                                            
B7 07 AD DE #                  LUI     x15, 0xDEAD0       # 268     
93 00 B0 07 #                  ADDI    x1,  x0, 123       # 272    # x1 = 123                                                                                                                                                                                                                               
37 01 0F 00 #                  LUI     x2,  0x000F0       # 276    # x2 = 0x000F0000 = 983040                                                                                                                                                           
13 01 81 1C #                  ADDI    x2,  x2, 456       # 280    # x2 = 983496                                                                                                                                                            
B3 81 20 02 #                  MUL     x3,  x1, x2        # 284    # x3 = 123 * 983496 = 120970008                                                                                                                                                          
33 C2 11 02 #                  DIV     x4,  x3, x1        # 288    # x4 = 120976008 / 123 = 983496 (should match x2)                                                                                                                                                            
B3 E2 11 02 #                  REM     x5,  x3, x1        # 292    # x5 = 120976008 % 123 = 0                                                                                                                                                           
37 03 20 00 #                  LUI     x6,  0x00200       # 296    # x6 = 0x00200000 = 2097152                                                                                                                                                          
93 03 70 FE #                  ADDI    x7,  x0, -25       # 300    # x7 = -25                                                                                                                                                           
33 04 73 02 #                  MUL     x8,  x6, x7        # 304    # x8 = 2097152 * -25 = -52428800                                                                                                                                                         
B3 44 74 02 #                  DIV     x9,  x8, x7        # 308    # x9 = -52428800 / -25 = 2097152 (back to x6)                                                                                                                                                            
33 65 74 02 #                  REM     x10, x8, x7        # 312    # x10 = -52428800 % -25 = 0                                                                                                                                                          
B3 05 13 02 #                  MUL     x11, x6, x1        # 316    # x11 = 2097152 * 123 = 257949696                                                                                                                                                            
63 84 B5 00 #                  BEQ     x11, x11, LABEL_3  # 320    # Always true → jump                                                                                                                                                         
13 06 70 3E #                  ADDI    x12, x0, 999       # 324    # Should be skipped    

B3 C6 15 02 #       LABEL_3:   DIV     x13, x11, x1       # 328    # x13 = 257949696 / 123 = 2097152                                                                                                                                                            
33 E7 15 02 #                  REM     x14, x11, x1       # 332    # x14 = 257949696 % 123 = 0                                                                                                                                                         
B3 87 10 02 #                  MUL     x15, x1, x1        # 336    # x15 = 123 * 123 = 15129                                                                                                                                                            
6F 08 80 00 #                  JAL     x16, LABEL_4       # 340    # Jump to label4, x16 = PC = 344                                                                                                                                                         
93 08 F0 0F #                  ADDI    x17, x0, 0x0FF     # 344    # Should be skipped                                                                                                                                                          
33 F9 17 02 #       LABEL_4:   REMU    x18, x15, x1       # 348    # x18 = 15129 % 123 = 0                                                                                                                                                          
B7 69 45 00 #                  LUI     x19, 0x00456       # 352    # x19 = 0x00456000 = 4546560                                                                                                                                                         
13 0A F0 01 #                  ADDI    x20, x0, 31        # 356    # x20 = 31                                                                                                                                                           
B3 9A 49 03 #                  MULH    x21, x19, x20      # 360    # x21 = high(4546560 * 31) = 0 (0x0866_A000)                                                                                                                                                          
33 BB 49 03 #                  MULHU   x22, x19, x20      # 364    # x22 = unsigned high of 4546560 * 31 = 0 (0x0866_A000)                                                                                                                                                             
B3 AB 49 03 #                  MULHSU  x23, x19, x20      # 368    # x23 = mixed signed/unsigned high = 0 (0x0866_A000)                                                                                                                                                            
13 0C 10 01 #                  ADDI    x24, x0, 17        # 372    # x24 = 17                                                                                                                                                           
B3 0C 3C 03 #                  MUL     x25, x24, x19      # 376    # x25 = 17 * 4546560 = 77291520                                                                                                                                                          
33 DD 8C 03 #                  DIVU    x26, x25, x24      # 380    # x26 = 77291520 / 17 = 4546560                                                                                                                                                          
B3 FD 8C 03 #                  REMU    x27, x25, x24      # 384    # x27 = 77291520 % 17 = 0                                                                                                                                                            
13 0E B0 0A #                  ADDI    x28, x0, 0xAB      # 388    # x28 = 0xAB = 171                                                                                                                                                         
93 0E 00 00 #                  ADDI    x29, x0, 0         # 392    # x29 = 0                                                                                                                                                            
33 4F DE 03 #                  DIV     x30, x28, x29      # 396    # x30 = 0 (undefined behavior, safe fallback)                                                                                                                                                            
B3 6F DE 03 #                  REM     x31, x28, x29      # 400    # x31 = 0 (safe fallback)                                                                                                                                                            








